/**
 * 50 unikal menyu şablon konsepti — ID sırası planTemplatePolicy MENU_TEMPLATE_IDS_ORDERED ilə eynidir.
 */
import { MENU_TEMPLATE_IDS_ORDERED } from "../../planTemplatePolicy";
import type {
  MenuTemplateDef,
  MenuTemplateTheme,
  TemplateCategory,
  HeaderLayout,
  ProductLayout,
  CategoryNavStyle,
  HeroVariant,
  CardStyle,
  Density,
  IconStyle,
  FontPairKey,
} from "./types";

type Tone = "light" | "luxury" | "dark" | "neon" | "warm" | "pastel";

type ConceptDim = {
  name: string;
  slug: string;
  tone: Tone;
  hue: number;
  headerLayout: HeaderLayout;
  productLayout: ProductLayout;
  categoryNav: CategoryNavStyle;
  cardStyle: CardStyle;
  heroVariant: HeroVariant;
  density: Density;
  radius: MenuTemplateTheme["radius"];
  productImageRadius: MenuTemplateTheme["productImageRadius"];
  heroPattern: MenuTemplateTheme["heroPattern"];
  iconStyle: IconStyle;
  headingWeight: MenuTemplateTheme["headingWeight"];
  showFab: boolean;
  showBottomNav: boolean;
  overlayPercent: number;
  fontI: number;
};

function hsl(h: number, s: number, l: number) {
  return `hsl(${h}, ${s}%, ${l}%)`;
}

/** 50 fərqli restoran / yemək görüntüsü */
const HERO_IMAGES: string[] = [
  "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=1200&q=80&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=1200&q=80&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1559339352-11d035aa65de?w=1200&q=80&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=1200&q=80&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1498654896293-37aacf113fd9?w=1200&q=80&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=1200&q=80&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=1200&q=80&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1552566626-52f8b828add9?w=1200&q=80&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=1200&q=80&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1476224203411-9f585f6ec80f?w=1200&q=80&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1466978913421-dad2ebd01d17?w=1200&q=80&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=1200&q=80&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1551218808-94e220e084d2?w=1200&q=80&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1481833761820-0509d3217039?w=1200&q=80&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1528605105345-5344ea20e61d?w=1200&q=80&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1544148103-0771bf50d2ab?w=1200&q=80&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1571997478779-2adcbbe9ab2f?w=1200&q=80&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1559339352-56e07322d453?w=1200&q=80&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1493770348161-369560ae357d?w=1200&q=80&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1521017432531-fbd92d768814?w=1200&q=80&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1574484284002-95289ed498a3?w=1200&q=80&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=1200&q=80&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=1200&q=80&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1600891964092-4316c288032e?w=1200&q=80&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1587899897387-091ebd01a6b0?w=1200&q=80&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1563379926898-05f4575a45d8?w=1200&q=80&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=1200&q=80&auto=format&fit=crop&sat=-30",
  "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=1200&q=80&auto=format&fit=crop&sat=10",
  "https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=1200&q=80&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1598215439218-f659816457ee?w=1200&q=80&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=1200&q=80&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=1200&q=80&auto=format&fit=crop&hue=10",
  "https://images.unsplash.com/photo-1604386344954-c69081578b97?w=1200&q=80&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1551218808-94e220e084d2?w=1200&q=80&auto=format&fit=crop&flip=h",
  "https://images.unsplash.com/photo-1484723091739-30a097e8f929?w=1200&q=80&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1499028344343-cd173ffc68a9?w=1200&q=80&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1515003197210-e0cd71810b5f?w=1200&q=80&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1533777326415-1f06cd3f1e90?w=1200&q=80&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=1200&q=80&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=1200&q=80&auto=format&fit=crop&flip=h",
  "https://images.unsplash.com/photo-1563371351280-52fa8d279ea4?w=1200&q=80&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1598511726623-2d0c9fd6b07a?w=1200&q=80&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1626645738196-c2d7e5c6a8c0?w=1200&q=80&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1432139509613-547c3da452d5?w=1200&q=80&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1585518419759-7fe2c9dd5e5b?w=1200&q=80&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1544025162-dab5424da621?w=1200&q=80&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1608039829572-11224e2e3096?w=1200&q=80&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=1200&q=80&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1505253758473-96b7017fcd40?w=1200&q=80&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1466978913421-dad2ebd01d17?w=1200&q=80&auto=format&fit=crop&sat=15",
  "https://images.unsplash.com/photo-1504754524776-8f4f37790ca0?w=1200&q=80&auto=format&fit=crop",
];

const CATEGORY_OF_INDEX = (i: number): TemplateCategory =>
  (["Modern", "Luxury", "Minimal", "Fast Food", "Cafe"] as const)[Math.floor(i / 10)]!;

/** 50 fərqli font cütlüyü — index.html-da əlavə Google fontlar */
const FONT_STACKS: { heading: string; body: string }[] = [
  { heading: "'Outfit', system-ui, sans-serif", body: "'Rubik', system-ui, sans-serif" },
  { heading: "'Playfair Display', Georgia, serif", body: "'IBM Plex Sans', system-ui, sans-serif" },
  { heading: "'Syne', system-ui, sans-serif", body: "'Manrope', system-ui, sans-serif" },
  { heading: "'Bebas Neue', Impact, sans-serif", body: "'Nunito', system-ui, sans-serif" },
  { heading: "'Fraunces', Georgia, serif", body: "'Plus Jakarta Sans', system-ui, sans-serif" },
  { heading: "'Space Grotesk', system-ui, sans-serif", body: "'DM Sans', system-ui, sans-serif" },
  { heading: "'Cormorant Garamond', Georgia, serif", body: "'Work Sans', system-ui, sans-serif" },
  { heading: "'Oswald', system-ui, sans-serif", body: "'Roboto', system-ui, sans-serif" },
  { heading: "'Montserrat', system-ui, sans-serif", body: "'Inter', system-ui, sans-serif" },
  { heading: "'Lora', Georgia, serif", body: "'Source Sans 3', system-ui, sans-serif" },
  { heading: "'Merriweather', Georgia, serif", body: "'Lato', system-ui, sans-serif" },
  { heading: "'Raleway', system-ui, sans-serif", body: "'Open Sans', system-ui, sans-serif" },
  { heading: "'Crimson Pro', Georgia, serif", body: "'Geologica', system-ui, sans-serif" },
  { heading: "'Archivo', system-ui, sans-serif", body: "'Lexend', system-ui, sans-serif" },
  { heading: "'Orbitron', system-ui, sans-serif", body: "'Exo 2', system-ui, sans-serif" },
  { heading: "'Righteous', fantasy, sans-serif", body: "'Barlow Condensed', system-ui, sans-serif" },
  { heading: "'Staatliches', system-ui, sans-serif", body: "'Urbanist', system-ui, sans-serif" },
  { heading: "'Anton', Impact, sans-serif", body: "'Sora', system-ui, sans-serif" },
  { heading: "'JetBrains Mono', monospace", body: "'Noto Sans', system-ui, sans-serif" },
  { heading: "'Dancing Script', cursive", body: "'IBM Plex Sans', system-ui, sans-serif" },
  { heading: "'Pacifico', cursive", body: "'Outfit', system-ui, sans-serif" },
  { heading: "'Caveat', cursive", body: "'Rubik', system-ui, sans-serif" },
  { heading: "'Press Start 2P', monospace", body: "'IBM Plex Sans', system-ui, sans-serif" },
  { heading: "'Black Ops One', fantasy, sans-serif", body: "'Inter', system-ui, sans-serif" },
  { heading: "'Teko', system-ui, sans-serif", body: "'Manrope', system-ui, sans-serif" },
  { heading: "'Libre Baskerville', Georgia, serif", body: "'Figtree', system-ui, sans-serif" },
  { heading: "'Sora', system-ui, sans-serif", body: "'Plus Jakarta Sans', system-ui, sans-serif" },
  { heading: "'Urbanist', system-ui, sans-serif", body: "'DM Sans', system-ui, sans-serif" },
  { heading: "'Lexend', system-ui, sans-serif", body: "'Source Sans 3', system-ui, sans-serif" },
  { heading: "'Geologica', system-ui, sans-serif", body: "'Nunito', system-ui, sans-serif" },
  { heading: "'Figtree', system-ui, sans-serif", body: "'Open Sans', system-ui, sans-serif" },
  { heading: "'EB Garamond', Georgia, serif", body: "'IBM Plex Sans', system-ui, sans-serif" },
  { heading: "'Arsenal', system-ui, sans-serif", body: "'Rubik', system-ui, sans-serif" },
  { heading: "'Bricolage Grotesque', system-ui, sans-serif", body: "'Inter', system-ui, sans-serif" },
  { heading: "'Chakra Petch', system-ui, sans-serif", body: "'Manrope', system-ui, sans-serif" },
  { heading: "'Bungee', system-ui, sans-serif", body: "'Outfit', system-ui, sans-serif" },
  { heading: "'Unbounded', system-ui, sans-serif", body: "'Lexend', system-ui, sans-serif" },
  { heading: "'Gloock', Georgia, serif", body: "'DM Sans', system-ui, sans-serif" },
  { heading: "'Gruppo', system-ui, sans-serif", body: "'Noto Sans', system-ui, sans-serif" },
  { heading: "'Instrument Serif', Georgia, serif", body: "'Plus Jakarta Sans', system-ui, sans-serif" },
  { heading: "'Josefin Sans', system-ui, sans-serif", body: "'Lato', system-ui, sans-serif" },
  { heading: "'Kanit', system-ui, sans-serif", body: "'Sora', system-ui, sans-serif" },
  { heading: "'Mada', system-ui, sans-serif", body: "'Source Sans 3', system-ui, sans-serif" },
  { heading: "'Maven Pro', system-ui, sans-serif", body: "'Nunito', system-ui, sans-serif" },
  { heading: "'Onest', system-ui, sans-serif", body: "'Open Sans', system-ui, sans-serif" },
  { heading: "'Oxanium', system-ui, sans-serif", body: "'IBM Plex Sans', system-ui, sans-serif" },
  { heading: "'Pathway Extreme', system-ui, sans-serif", body: "'Urbanist', system-ui, sans-serif" },
  { heading: "'Petrona', Georgia, serif", body: "'Inter', system-ui, sans-serif" },
  { heading: "'Questrial', system-ui, sans-serif", body: "'Manrope', system-ui, sans-serif" },
  { heading: "'Red Hat Display', system-ui, sans-serif", body: "'Rubik', system-ui, sans-serif" },
  { heading: "'Signika Negative', system-ui, sans-serif", body: "'Outfit', system-ui, sans-serif" },
];

function buildTheme(d: ConceptDim): MenuTemplateTheme {
  const fontPair: FontPairKey = "montserrat-inter";
  const customFonts = FONT_STACKS[d.fontI % FONT_STACKS.length]!;

  const common = {
    fontPair,
    headingWeight: d.headingWeight,
    radius: d.radius,
    cardStyle: d.cardStyle,
    heroVariant: d.heroVariant,
    categoryNav: d.categoryNav,
    density: d.density,
    showFab: d.showFab,
    showBottomNav: d.showBottomNav,
    overlayPercent: d.overlayPercent,
    productImageRadius: d.productImageRadius,
    heroPattern: d.heroPattern,
    headerLayout: d.headerLayout,
    productLayout: d.productLayout,
    iconStyle: d.iconStyle,
    renderMode: d.slug,
    customFonts,
  } satisfies Partial<MenuTemplateTheme>;

  if (d.tone === "luxury") {
    return {
      ...common,
      primary: hsl(43, 78, 44 + (d.hue % 6)),
      secondary: hsl(38, 32, 16),
      accent: hsl(36, 85, 58),
      background: hsl(0, 0, 5 + (d.hue % 4)),
      surface: hsl(35, 8, 10),
      text: hsl(42, 25, 96),
      muted: hsl(40, 10, 62),
    } as MenuTemplateTheme;
  }

  if (d.tone === "dark") {
    const h = d.hue;
    return {
      ...common,
      primary: hsl(h, 72, 58),
      secondary: hsl(h, 12, 18),
      accent: hsl((h + 145) % 360, 62, 55),
      background: hsl(222, 16, 7),
      surface: hsl(222, 14, 11),
      text: hsl(210, 25, 96),
      muted: hsl(217, 12, 58),
    } as MenuTemplateTheme;
  }

  if (d.tone === "neon") {
    return {
      ...common,
      primary: "#22d3ee",
      secondary: "#4c1d95",
      accent: "#f472b6",
      background: "#030712",
      surface: "#0f172a",
      text: "#f8fafc",
      muted: "#94a3b8",
    } as MenuTemplateTheme;
  }

  if (d.tone === "pastel") {
    const h = d.hue;
    return {
      ...common,
      primary: hsl(h, 45, 55),
      secondary: hsl((h + 40) % 360, 35, 88),
      accent: hsl((h + 200) % 360, 42, 62),
      background: hsl(h, 38, 97),
      surface: hsl(0, 0, 100),
      text: hsl(h, 22, 22),
      muted: hsl(h, 12, 48),
    } as MenuTemplateTheme;
  }

  if (d.tone === "warm") {
    const h = 24 + (d.hue % 12);
    return {
      ...common,
      primary: hsl(h, 55, 34),
      secondary: hsl(h, 38, 88),
      accent: hsl((h + 300) % 360, 50, 48),
      background: hsl(h, 48, 95),
      surface: hsl(35, 60, 99),
      text: hsl(h, 45, 16),
      muted: hsl(h, 16, 42),
    } as MenuTemplateTheme;
  }

  const h = d.hue;
  return {
    ...common,
    primary: hsl(h, 72, 44),
    secondary: hsl(h, 35, 91),
    accent: hsl((h + 48) % 360, 68, 48),
    background: hsl(h, 28, 97),
    surface: "#ffffff",
    text: hsl(h, 35, 12),
    muted: hsl(h, 14, 42),
  } as MenuTemplateTheme;
}

/**
 * Sıra: bütün 50 UI konsept adı (Modern×10, Luxury×10, …)
 */
const CONCEPTS: ConceptDim[] = [
  {
    name: "Modern Gradient UI",
    slug: "modern-gradient-ui",
    tone: "light",
    hue: 292,
    headerLayout: "split",
    productLayout: "grid",
    categoryNav: "pills",
    cardStyle: "glass",
    heroVariant: "wave",
    density: "comfortable",
    radius: "2xl",
    productImageRadius: "xl",
    heroPattern: "dots",
    iconStyle: "rounded",
    headingWeight: "font-bold",
    showFab: true,
    showBottomNav: false,
    overlayPercent: 42,
    fontI: 0,
  },
  {
    name: "Soft Pastel Colors",
    slug: "soft-pastel-colors",
    tone: "pastel",
    hue: 320,
    headerLayout: "centered",
    productLayout: "card",
    categoryNav: "tabs",
    cardStyle: "elevated",
    heroVariant: "compact",
    density: "spacious",
    radius: "full",
    productImageRadius: "2xl",
    heroPattern: "noise",
    iconStyle: "line",
    headingWeight: "font-semibold",
    showFab: true,
    showBottomNav: false,
    overlayPercent: 30,
    fontI: 1,
  },
  {
    name: "Neon Cyberpunk",
    slug: "neon-cyberpunk",
    tone: "neon",
    hue: 195,
    headerLayout: "side",
    productLayout: "list",
    categoryNav: "scroll",
    cardStyle: "bordered",
    heroVariant: "fullscreen",
    density: "compact",
    radius: "md",
    productImageRadius: "md",
    heroPattern: "grid",
    iconStyle: "filled",
    headingWeight: "font-black",
    showFab: true,
    showBottomNav: true,
    overlayPercent: 60,
    fontI: 2,
  },
  {
    name: "3D Floating Cards UI",
    slug: "floating-3d-cards",
    tone: "light",
    hue: 168,
    headerLayout: "full-hero",
    productLayout: "card",
    categoryNav: "pills",
    cardStyle: "elevated",
    heroVariant: "wave",
    density: "comfortable",
    radius: "xl",
    productImageRadius: "2xl",
    heroPattern: "dots",
    iconStyle: "rounded",
    headingWeight: "font-bold",
    showFab: true,
    showBottomNav: false,
    overlayPercent: 38,
    fontI: 3,
  },
  {
    name: "Split Screen Layout",
    slug: "split-screen-layout",
    tone: "light",
    hue: 225,
    headerLayout: "split",
    productLayout: "list",
    categoryNav: "underline",
    cardStyle: "flat",
    heroVariant: "split",
    density: "comfortable",
    radius: "lg",
    productImageRadius: "lg",
    heroPattern: "none",
    iconStyle: "minimal",
    headingWeight: "font-semibold",
    showFab: true,
    showBottomNav: false,
    overlayPercent: 35,
    fontI: 4,
  },
  {
    name: "Full Screen Hero Image",
    slug: "full-screen-hero-image",
    tone: "light",
    hue: 14,
    headerLayout: "full-hero",
    productLayout: "grid",
    categoryNav: "scroll",
    cardStyle: "glass",
    heroVariant: "fullscreen",
    density: "comfortable",
    radius: "2xl",
    productImageRadius: "xl",
    heroPattern: "noise",
    iconStyle: "rounded",
    headingWeight: "font-bold",
    showFab: true,
    showBottomNav: false,
    overlayPercent: 50,
    fontI: 5,
  },
  {
    name: "Dark Mode Minimal",
    slug: "dark-mode-minimal",
    tone: "dark",
    hue: 215,
    headerLayout: "centered",
    productLayout: "list",
    categoryNav: "tabs",
    cardStyle: "bordered",
    heroVariant: "compact",
    density: "compact",
    radius: "sm",
    productImageRadius: "md",
    heroPattern: "grid",
    iconStyle: "line",
    headingWeight: "font-normal",
    showFab: false,
    showBottomNav: false,
    overlayPercent: 55,
    fontI: 6,
  },
  {
    name: "3D Product Showcase",
    slug: "product-3d-showcase",
    tone: "light",
    hue: 32,
    headerLayout: "side",
    productLayout: "slider",
    categoryNav: "pills",
    cardStyle: "elevated",
    heroVariant: "wave",
    density: "spacious",
    radius: "2xl",
    productImageRadius: "2xl",
    heroPattern: "dots",
    iconStyle: "filled",
    headingWeight: "font-bold",
    showFab: true,
    showBottomNav: false,
    overlayPercent: 40,
    fontI: 7,
  },
  {
    name: "Blur Background Modern",
    slug: "blur-background-modern",
    tone: "light",
    hue: 200,
    headerLayout: "centered",
    productLayout: "grid",
    categoryNav: "pills",
    cardStyle: "glass",
    heroVariant: "compact",
    density: "comfortable",
    radius: "xl",
    productImageRadius: "lg",
    heroPattern: "noise",
    iconStyle: "rounded",
    headingWeight: "font-semibold",
    showFab: true,
    showBottomNav: false,
    overlayPercent: 33,
    fontI: 8,
  },
  {
    name: "Tech Startup UI",
    slug: "tech-startup-ui",
    tone: "light",
    hue: 252,
    headerLayout: "split",
    productLayout: "list",
    categoryNav: "underline",
    cardStyle: "flat",
    heroVariant: "split",
    density: "compact",
    radius: "md",
    productImageRadius: "md",
    heroPattern: "grid",
    iconStyle: "line",
    headingWeight: "font-bold",
    showFab: true,
    showBottomNav: true,
    overlayPercent: 36,
    fontI: 9,
  },

  {
    name: "Dark Luxury Gold",
    slug: "dark-luxury-gold",
    tone: "luxury",
    hue: 43,
    headerLayout: "full-hero",
    productLayout: "card",
    categoryNav: "tabs",
    cardStyle: "glass",
    heroVariant: "fullscreen",
    density: "spacious",
    radius: "lg",
    productImageRadius: "lg",
    heroPattern: "dots",
    iconStyle: "filled",
    headingWeight: "font-light",
    showFab: true,
    showBottomNav: false,
    overlayPercent: 58,
    fontI: 10,
  },
  {
    name: "Luxury Restaurant Elegant",
    slug: "luxury-restaurant-elegant",
    tone: "luxury",
    hue: 48,
    headerLayout: "split",
    productLayout: "list",
    categoryNav: "underline",
    cardStyle: "bordered",
    heroVariant: "wave",
    density: "spacious",
    radius: "none",
    productImageRadius: "sm",
    heroPattern: "noise",
    iconStyle: "line",
    headingWeight: "font-light",
    showFab: true,
    showBottomNav: false,
    overlayPercent: 52,
    fontI: 11,
  },
  {
    name: "Premium Black & White",
    slug: "premium-black-white",
    tone: "luxury",
    hue: 40,
    headerLayout: "centered",
    productLayout: "grid",
    categoryNav: "scroll",
    cardStyle: "flat",
    heroVariant: "compact",
    density: "comfortable",
    radius: "sm",
    productImageRadius: "sm",
    heroPattern: "none",
    iconStyle: "minimal",
    headingWeight: "font-normal",
    showFab: false,
    showBottomNav: false,
    overlayPercent: 48,
    fontI: 12,
  },
  {
    name: "Elegant Serif Font Style",
    slug: "elegant-serif-style",
    tone: "luxury",
    hue: 46,
    headerLayout: "side",
    productLayout: "card",
    categoryNav: "pills",
    cardStyle: "elevated",
    heroVariant: "split",
    density: "spacious",
    radius: "xl",
    productImageRadius: "xl",
    heroPattern: "dots",
    iconStyle: "rounded",
    headingWeight: "font-light",
    showFab: true,
    showBottomNav: false,
    overlayPercent: 45,
    fontI: 13,
  },
  {
    name: "Luxury Hotel Style",
    slug: "luxury-hotel-style",
    tone: "luxury",
    hue: 210,
    headerLayout: "full-hero",
    productLayout: "list",
    categoryNav: "tabs",
    cardStyle: "bordered",
    heroVariant: "fullscreen",
    density: "spacious",
    radius: "2xl",
    productImageRadius: "2xl",
    heroPattern: "grid",
    iconStyle: "filled",
    headingWeight: "font-semibold",
    showFab: true,
    showBottomNav: true,
    overlayPercent: 55,
    fontI: 14,
  },
  {
    name: "Metallic 3D UI",
    slug: "metallic-3d-ui",
    tone: "luxury",
    hue: 200,
    headerLayout: "split",
    productLayout: "grid",
    categoryNav: "underline",
    cardStyle: "elevated",
    heroVariant: "wave",
    density: "comfortable",
    radius: "md",
    productImageRadius: "xl",
    heroPattern: "noise",
    iconStyle: "line",
    headingWeight: "font-bold",
    showFab: true,
    showBottomNav: false,
    overlayPercent: 50,
    fontI: 15,
  },
  {
    name: "Retro Vintage UI",
    slug: "retro-vintage-ui",
    tone: "warm",
    hue: 15,
    headerLayout: "centered",
    productLayout: "slider",
    categoryNav: "scroll",
    cardStyle: "bordered",
    heroVariant: "compact",
    density: "comfortable",
    radius: "sm",
    productImageRadius: "md",
    heroPattern: "dots",
    iconStyle: "filled",
    headingWeight: "font-black",
    showFab: true,
    showBottomNav: false,
    overlayPercent: 44,
    fontI: 16,
  },
  {
    name: "Fullscreen Swipe Menu",
    slug: "fullscreen-swipe-menu",
    tone: "luxury",
    hue: 38,
    headerLayout: "full-hero",
    productLayout: "slider",
    categoryNav: "pills",
    cardStyle: "glass",
    heroVariant: "fullscreen",
    density: "compact",
    radius: "full",
    productImageRadius: "2xl",
    heroPattern: "none",
    iconStyle: "rounded",
    headingWeight: "font-semibold",
    showFab: true,
    showBottomNav: true,
    overlayPercent: 62,
    fontI: 17,
  },
  {
    name: "Image Overlay Text UI",
    slug: "image-overlay-text-ui",
    tone: "luxury",
    hue: 44,
    headerLayout: "full-hero",
    productLayout: "card",
    categoryNav: "tabs",
    cardStyle: "flat",
    heroVariant: "fullscreen",
    density: "spacious",
    radius: "2xl",
    productImageRadius: "xl",
    heroPattern: "grid",
    iconStyle: "minimal",
    headingWeight: "font-light",
    showFab: true,
    showBottomNav: false,
    overlayPercent: 65,
    fontI: 18,
  },
  {
    name: "Interactive Motion UI",
    slug: "interactive-motion-ui",
    tone: "luxury",
    hue: 36,
    headerLayout: "side",
    productLayout: "grid",
    categoryNav: "underline",
    cardStyle: "elevated",
    heroVariant: "wave",
    density: "comfortable",
    radius: "xl",
    productImageRadius: "lg",
    heroPattern: "dots",
    iconStyle: "line",
    headingWeight: "font-bold",
    showFab: true,
    showBottomNav: false,
    overlayPercent: 41,
    fontI: 19,
  },

  {
    name: "Minimal White Clean",
    slug: "minimal-white-clean",
    tone: "light",
    hue: 0,
    headerLayout: "centered",
    productLayout: "list",
    categoryNav: "underline",
    cardStyle: "flat",
    heroVariant: "compact",
    density: "spacious",
    radius: "none",
    productImageRadius: "sm",
    heroPattern: "none",
    iconStyle: "line",
    headingWeight: "font-semibold",
    showFab: false,
    showBottomNav: false,
    overlayPercent: 22,
    fontI: 20,
  },
  {
    name: "List Style Minimal",
    slug: "list-style-minimal",
    tone: "light",
    hue: 210,
    headerLayout: "split",
    productLayout: "list",
    categoryNav: "tabs",
    cardStyle: "flat",
    heroVariant: "split",
    density: "compact",
    radius: "sm",
    productImageRadius: "md",
    heroPattern: "none",
    iconStyle: "minimal",
    headingWeight: "font-normal",
    showFab: true,
    showBottomNav: false,
    overlayPercent: 28,
    fontI: 21,
  },
  {
    name: "Minimal Text Heavy UI",
    slug: "minimal-text-heavy",
    tone: "light",
    hue: 0,
    headerLayout: "centered",
    productLayout: "list",
    categoryNav: "scroll",
    cardStyle: "bordered",
    heroVariant: "compact",
    density: "comfortable",
    radius: "md",
    productImageRadius: "sm",
    heroPattern: "grid",
    iconStyle: "minimal",
    headingWeight: "font-bold",
    showFab: false,
    showBottomNav: false,
    overlayPercent: 25,
    fontI: 22,
  },
  {
    name: "Flat Design Modern",
    slug: "flat-design-modern",
    tone: "light",
    hue: 185,
    headerLayout: "split",
    productLayout: "grid",
    categoryNav: "pills",
    cardStyle: "flat",
    heroVariant: "split",
    density: "comfortable",
    radius: "none",
    productImageRadius: "md",
    heroPattern: "dots",
    iconStyle: "filled",
    headingWeight: "font-bold",
    showFab: true,
    showBottomNav: false,
    overlayPercent: 30,
    fontI: 23,
  },
  {
    name: "Sidebar Menu Style",
    slug: "sidebar-menu-style",
    tone: "light",
    hue: 220,
    headerLayout: "side",
    productLayout: "list",
    categoryNav: "tabs",
    cardStyle: "bordered",
    heroVariant: "compact",
    density: "compact",
    radius: "lg",
    productImageRadius: "lg",
    heroPattern: "none",
    iconStyle: "rounded",
    headingWeight: "font-semibold",
    showFab: true,
    showBottomNav: false,
    overlayPercent: 32,
    fontI: 24,
  },
  {
    name: "Horizontal Scroll Menu",
    slug: "horizontal-scroll-menu",
    tone: "light",
    hue: 175,
    headerLayout: "centered",
    productLayout: "slider",
    categoryNav: "scroll",
    cardStyle: "elevated",
    heroVariant: "wave",
    density: "comfortable",
    radius: "xl",
    productImageRadius: "xl",
    heroPattern: "noise",
    iconStyle: "rounded",
    headingWeight: "font-bold",
    showFab: true,
    showBottomNav: false,
    overlayPercent: 36,
    fontI: 25,
  },
  {
    name: "Compact Fast UI",
    slug: "compact-fast-ui",
    tone: "light",
    hue: 205,
    headerLayout: "centered",
    productLayout: "grid",
    categoryNav: "pills",
    cardStyle: "flat",
    heroVariant: "compact",
    density: "compact",
    radius: "md",
    productImageRadius: "md",
    heroPattern: "none",
    iconStyle: "filled",
    headingWeight: "font-black",
    showFab: true,
    showBottomNav: true,
    overlayPercent: 26,
    fontI: 26,
  },
  {
    name: "Rounded Soft UI",
    slug: "rounded-soft-ui",
    tone: "pastel",
    hue: 280,
    headerLayout: "centered",
    productLayout: "card",
    categoryNav: "pills",
    cardStyle: "elevated",
    heroVariant: "compact",
    density: "spacious",
    radius: "full",
    productImageRadius: "2xl",
    heroPattern: "noise",
    iconStyle: "rounded",
    headingWeight: "font-semibold",
    showFab: true,
    showBottomNav: false,
    overlayPercent: 28,
    fontI: 27,
  },
  {
    name: "Organic Shape UI",
    slug: "organic-shape-ui",
    tone: "pastel",
    hue: 140,
    headerLayout: "full-hero",
    productLayout: "grid",
    categoryNav: "tabs",
    cardStyle: "glass",
    heroVariant: "wave",
    density: "comfortable",
    radius: "2xl",
    productImageRadius: "2xl",
    heroPattern: "dots",
    iconStyle: "line",
    headingWeight: "font-bold",
    showFab: true,
    showBottomNav: false,
    overlayPercent: 34,
    fontI: 28,
  },
  {
    name: "Shadow Depth UI",
    slug: "shadow-depth-ui",
    tone: "dark",
    hue: 260,
    headerLayout: "split",
    productLayout: "card",
    categoryNav: "underline",
    cardStyle: "elevated",
    heroVariant: "split",
    density: "comfortable",
    radius: "lg",
    productImageRadius: "xl",
    heroPattern: "grid",
    iconStyle: "rounded",
    headingWeight: "font-bold",
    showFab: true,
    showBottomNav: false,
    overlayPercent: 48,
    fontI: 29,
  },

  {
    name: "Fast Food Bold UI",
    slug: "fast-food-bold-ui",
    tone: "light",
    hue: 8,
    headerLayout: "centered",
    productLayout: "grid",
    categoryNav: "pills",
    cardStyle: "elevated",
    heroVariant: "wave",
    density: "comfortable",
    radius: "xl",
    productImageRadius: "xl",
    heroPattern: "dots",
    iconStyle: "filled",
    headingWeight: "font-black",
    showFab: true,
    showBottomNav: true,
    overlayPercent: 32,
    fontI: 30,
  },
  {
    name: "Street Food Style",
    slug: "street-food-style",
    tone: "warm",
    hue: 28,
    headerLayout: "side",
    productLayout: "list",
    categoryNav: "scroll",
    cardStyle: "bordered",
    heroVariant: "compact",
    density: "compact",
    radius: "md",
    productImageRadius: "lg",
    heroPattern: "noise",
    iconStyle: "line",
    headingWeight: "font-bold",
    showFab: true,
    showBottomNav: false,
    overlayPercent: 38,
    fontI: 31,
  },
  {
    name: "Bottom Navigation UI",
    slug: "bottom-navigation-ui",
    tone: "light",
    hue: 350,
    headerLayout: "full-hero",
    productLayout: "grid",
    categoryNav: "tabs",
    cardStyle: "flat",
    heroVariant: "fullscreen",
    density: "comfortable",
    radius: "lg",
    productImageRadius: "md",
    heroPattern: "grid",
    iconStyle: "filled",
    headingWeight: "font-bold",
    showFab: true,
    showBottomNav: true,
    overlayPercent: 40,
    fontI: 32,
  },
  {
    name: "Grid Based Product Layout",
    slug: "grid-product-layout",
    tone: "light",
    hue: 15,
    headerLayout: "split",
    productLayout: "grid",
    categoryNav: "pills",
    cardStyle: "flat",
    heroVariant: "split",
    density: "compact",
    radius: "sm",
    productImageRadius: "md",
    heroPattern: "none",
    iconStyle: "rounded",
    headingWeight: "font-bold",
    showFab: true,
    showBottomNav: false,
    overlayPercent: 29,
    fontI: 33,
  },
  {
    name: "Animated Category Tabs",
    slug: "animated-category-tabs",
    tone: "light",
    hue: 340,
    headerLayout: "centered",
    productLayout: "list",
    categoryNav: "tabs",
    cardStyle: "elevated",
    heroVariant: "compact",
    density: "comfortable",
    radius: "xl",
    productImageRadius: "lg",
    heroPattern: "dots",
    iconStyle: "rounded",
    headingWeight: "font-semibold",
    showFab: true,
    showBottomNav: false,
    overlayPercent: 33,
    fontI: 34,
  },
  {
    name: "3D Icon Based UI",
    slug: "icon-3d-ui",
    tone: "light",
    hue: 48,
    headerLayout: "full-hero",
    productLayout: "card",
    categoryNav: "pills",
    cardStyle: "elevated",
    heroVariant: "wave",
    density: "spacious",
    radius: "2xl",
    productImageRadius: "2xl",
    heroPattern: "grid",
    iconStyle: "filled",
    headingWeight: "font-black",
    showFab: true,
    showBottomNav: false,
    overlayPercent: 37,
    fontI: 35,
  },
  {
    name: "Colorful Gradient Cards",
    slug: "colorful-gradient-cards",
    tone: "pastel",
    hue: 265,
    headerLayout: "split",
    productLayout: "card",
    categoryNav: "scroll",
    cardStyle: "glass",
    heroVariant: "split",
    density: "comfortable",
    radius: "2xl",
    productImageRadius: "xl",
    heroPattern: "noise",
    iconStyle: "line",
    headingWeight: "font-bold",
    showFab: true,
    showBottomNav: false,
    overlayPercent: 35,
    fontI: 36,
  },
  {
    name: "Instagram Style Feed Menu",
    slug: "instagram-feed-menu",
    tone: "light",
    hue: 330,
    headerLayout: "centered",
    productLayout: "grid",
    categoryNav: "pills",
    cardStyle: "flat",
    heroVariant: "compact",
    density: "compact",
    radius: "md",
    productImageRadius: "md",
    heroPattern: "none",
    iconStyle: "minimal",
    headingWeight: "font-semibold",
    showFab: true,
    showBottomNav: false,
    overlayPercent: 27,
    fontI: 37,
  },
  {
    name: "TikTok Style Vertical Scroll",
    slug: "tiktok-vertical-menu",
    tone: "dark",
    hue: 280,
    headerLayout: "full-hero",
    productLayout: "list",
    categoryNav: "scroll",
    cardStyle: "bordered",
    heroVariant: "fullscreen",
    density: "compact",
    radius: "lg",
    productImageRadius: "xl",
    heroPattern: "none",
    iconStyle: "filled",
    headingWeight: "font-bold",
    showFab: true,
    showBottomNav: true,
    overlayPercent: 56,
    fontI: 38,
  },
  {
    name: "Futuristic UI",
    slug: "futuristic-ui",
    tone: "neon",
    hue: 190,
    headerLayout: "split",
    productLayout: "grid",
    categoryNav: "underline",
    cardStyle: "bordered",
    heroVariant: "split",
    density: "comfortable",
    radius: "md",
    productImageRadius: "md",
    heroPattern: "grid",
    iconStyle: "line",
    headingWeight: "font-bold",
    showFab: true,
    showBottomNav: false,
    overlayPercent: 58,
    fontI: 39,
  },

  {
    name: "Glassmorphism UI",
    slug: "glassmorphism-ui",
    tone: "light",
    hue: 195,
    headerLayout: "full-hero",
    productLayout: "card",
    categoryNav: "pills",
    cardStyle: "glass",
    heroVariant: "wave",
    density: "spacious",
    radius: "2xl",
    productImageRadius: "2xl",
    heroPattern: "noise",
    iconStyle: "rounded",
    headingWeight: "font-semibold",
    showFab: true,
    showBottomNav: false,
    overlayPercent: 36,
    fontI: 40,
  },
  {
    name: "Cafe Warm Style",
    slug: "cafe-warm-style",
    tone: "warm",
    hue: 30,
    headerLayout: "centered",
    productLayout: "grid",
    categoryNav: "tabs",
    cardStyle: "elevated",
    heroVariant: "compact",
    density: "comfortable",
    radius: "xl",
    productImageRadius: "lg",
    heroPattern: "dots",
    iconStyle: "rounded",
    headingWeight: "font-semibold",
    showFab: true,
    showBottomNav: false,
    overlayPercent: 39,
    fontI: 41,
  },
  {
    name: "Card Slider Layout",
    slug: "card-slider-layout",
    tone: "warm",
    hue: 22,
    headerLayout: "side",
    productLayout: "slider",
    categoryNav: "scroll",
    cardStyle: "elevated",
    heroVariant: "wave",
    density: "comfortable",
    radius: "xl",
    productImageRadius: "xl",
    heroPattern: "noise",
    iconStyle: "filled",
    headingWeight: "font-bold",
    showFab: true,
    showBottomNav: false,
    overlayPercent: 41,
    fontI: 42,
  },
  {
    name: "Full Image Background Menu",
    slug: "full-image-background-menu",
    tone: "warm",
    hue: 18,
    headerLayout: "full-hero",
    productLayout: "list",
    categoryNav: "pills",
    cardStyle: "glass",
    heroVariant: "fullscreen",
    density: "spacious",
    radius: "2xl",
    productImageRadius: "2xl",
    heroPattern: "none",
    iconStyle: "minimal",
    headingWeight: "font-light",
    showFab: true,
    showBottomNav: false,
    overlayPercent: 52,
    fontI: 43,
  },
  {
    name: "Food Focus Large Images",
    slug: "food-focus-large-images",
    tone: "warm",
    hue: 26,
    headerLayout: "centered",
    productLayout: "card",
    categoryNav: "underline",
    cardStyle: "flat",
    heroVariant: "compact",
    density: "spacious",
    radius: "xl",
    productImageRadius: "2xl",
    heroPattern: "dots",
    iconStyle: "rounded",
    headingWeight: "font-bold",
    showFab: true,
    showBottomNav: false,
    overlayPercent: 31,
    fontI: 44,
  },
  {
    name: "Dark + Neon Buttons",
    slug: "dark-neon-buttons",
    tone: "neon",
    hue: 280,
    headerLayout: "centered",
    productLayout: "grid",
    categoryNav: "tabs",
    cardStyle: "bordered",
    heroVariant: "compact",
    density: "compact",
    radius: "lg",
    productImageRadius: "md",
    heroPattern: "grid",
    iconStyle: "filled",
    headingWeight: "font-black",
    showFab: true,
    showBottomNav: true,
    overlayPercent: 54,
    fontI: 45,
  },
  {
    name: "Story Mode Menu UI",
    slug: "story-mode-menu",
    tone: "light",
    hue: 310,
    headerLayout: "full-hero",
    productLayout: "slider",
    categoryNav: "scroll",
    cardStyle: "elevated",
    heroVariant: "fullscreen",
    density: "comfortable",
    radius: "full",
    productImageRadius: "lg",
    heroPattern: "none",
    iconStyle: "rounded",
    headingWeight: "font-semibold",
    showFab: true,
    showBottomNav: false,
    overlayPercent: 43,
    fontI: 46,
  },
  {
    name: "Animated Loading Menu",
    slug: "animated-loading-menu",
    tone: "light",
    hue: 200,
    headerLayout: "split",
    productLayout: "grid",
    categoryNav: "pills",
    cardStyle: "glass",
    heroVariant: "split",
    density: "comfortable",
    radius: "xl",
    productImageRadius: "lg",
    heroPattern: "grid",
    iconStyle: "line",
    headingWeight: "font-bold",
    showFab: true,
    showBottomNav: false,
    overlayPercent: 34,
    fontI: 47,
  },
  {
    name: "Cafe Cozy UI",
    slug: "cafe-cozy-ui",
    tone: "warm",
    hue: 35,
    headerLayout: "centered",
    productLayout: "list",
    categoryNav: "tabs",
    cardStyle: "elevated",
    heroVariant: "compact",
    density: "spacious",
    radius: "2xl",
    productImageRadius: "xl",
    heroPattern: "noise",
    iconStyle: "rounded",
    headingWeight: "font-semibold",
    showFab: true,
    showBottomNav: true,
    overlayPercent: 37,
    fontI: 48,
  },
  {
    name: "Fancy Animation UI",
    slug: "fancy-animation-ui",
    tone: "pastel",
    hue: 305,
    headerLayout: "side",
    productLayout: "card",
    categoryNav: "underline",
    cardStyle: "elevated",
    heroVariant: "wave",
    density: "comfortable",
    radius: "2xl",
    productImageRadius: "xl",
    heroPattern: "dots",
    iconStyle: "filled",
    headingWeight: "font-bold",
    showFab: true,
    showBottomNav: false,
    overlayPercent: 39,
    fontI: 49,
  },
];

function assertLength50() {
  if (CONCEPTS.length !== 50) {
    throw new Error(`conceptRegistry: expected 50 concepts, got ${CONCEPTS.length}`);
  }
  if (MENU_TEMPLATE_IDS_ORDERED.length !== 50) {
    throw new Error(`planTemplatePolicy expects 50 ids, got ${MENU_TEMPLATE_IDS_ORDERED.length}`);
  }
}

export function buildConceptMenuTemplates(): MenuTemplateDef[] {
  assertLength50();
  return MENU_TEMPLATE_IDS_ORDERED.map((id, i) => {
    const c = CONCEPTS[i]!;
    const theme = buildTheme(c);
    const category = CATEGORY_OF_INDEX(i);
    return {
      id,
      name: c.name,
      category,
      description: `${c.slug} · ${theme.headerLayout} · ${theme.productLayout} · ${theme.heroVariant}`,
      heroImage: HERO_IMAGES[i]!,
      theme,
    };
  });
}
